version: '3'


services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
  client-gateway:
    build: ./client-gateway
    ports: 
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVER=nats://nats-server:4222
  
  products-ms:
    build: ./ms-product
    volumes:
      - ./ms-product/src:/usr/src/app/src
      - ./ms-product/dev.db:/usr/src/app/dev.db
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db    

  order-ms:
    depends_on:
      - orders-db
    build: ./ms-order
    volumes:
      - ./ms-order/src:/usr/src/app/src
    command: sh -c "sleep 5 && npm run start:dev"
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123456@orders-database:5432/ordersdb?schema=public
      - NATS_SERVER=nats://nats-server:4222

  orders-db:
    container_name: orders-database
    image: postgres:16.2
    restart: always
    volumes:
      - ./ms-order/postgres:/var/lib/postgresql/data # Persistencia de datos: monta un volumen para almacenar los datos de PostgreSQL en el host local 
    ports:
      - 55432:5432 # Mapea el puerto 5432 del contenedor al puerto 5432 del host local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ordersdb

  payments-ms:
    container_name: ms-payments
    build: ./ms-payments
    ports:
      - ${PAYMENTS_MS_PORT}:3003
    volumes:
      - ./ms-payments/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - CLIENT_ID_SANDBOX=${CLIENT_ID_SANDBOX}
      - CLIENT_SECRET_SANDBOX=${CLIENT_SECRET_SANDBOX}
      - WEBHOOK_ID_SANDBOX=${WEBHOOK_ID_SANDBOX}
      - DOMAIN_PAYPAL_SANBOX=${DOMAIN_PAYPAL_SANBOX}